services:
  # PostgreSQL Database
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lollylaw
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lollylaw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node server.js"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/lollylaw
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - url=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lollylaw-network
    restart: unless-stopped

networks:
  lollylaw-network:
    driver: bridge

volumes:
  psql: